<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><StartupObject>UiTests</StartupObject></PropertyGroup><ItemGroup><ProjectReference Include="../../src/EliteGraphics.App/EliteGraphics.App.csproj" /></ItemGroup></Project>
