using System.Text;
using EliteGraphics.Core;

var root=Path.Combine(Path.GetTempPath(),"egc-tests-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);
var definitions=Encoding.UTF8.GetBytes("""
<GraphicsConfig><Planets><Low><TextureSize>512</TextureSize></Low><Medium><TextureSize>1024</TextureSize><WorkPerFrame>132</WorkPerFrame></Medium><High><TextureSize>2048</TextureSize></High><Ultra><TextureSize>2560</TextureSize></Ultra></Planets><GalaxyBackground><Low><TextureSize>512</TextureSize></Low><Medium><TextureSize>1024</TextureSize></Medium><High><TextureSize>2048</TextureSize></High></GalaxyBackground><Environment><Low><Item><Feature>Planets</Feature><QualitySetting>0</QualitySetting></Item><Item><Feature>GalaxyBackground</Feature><QualitySetting>0</QualitySetting></Item></Low><Medium><Item><Feature>Planets</Feature><QualitySetting>1</QualitySetting></Item><Item><Feature>GalaxyBackground</Feature><QualitySetting>1</QualitySetting></Item></Medium><High><Item><Feature>Planets</Feature><QualitySetting>2</QualitySetting></Item><Item><Feature>GalaxyBackground</Feature><QualitySetting>2</QualitySetting></Item></High><Ultra><Item><Feature>Planets</Feature><QualitySetting>3</QualitySetting></Item><Item><Feature>GalaxyBackground</Feature><QualitySetting>2</QualitySetting></Item></Ultra></Environment></GraphicsConfig>
""");
FileSet Baseline(string version="4.4")=>new(){["Settings.xml"]=Encoding.UTF8.GetBytes("<GraphicsOptions><PresetName>Custom</PresetName><StereoscopicMode>3</StereoscopicMode><TerrainCheckerboardRenderingEnabled>true</TerrainCheckerboardRenderingEnabled></GraphicsOptions>"),["Custom."+version+".fxcfg"]=Encoding.UTF8.GetBytes($"<Root MajorVersion='{version.Split('.')[0]}' MinorVersion='{version.Split('.')[1]}'><EnvironmentQuality>1</EnvironmentQuality><HMDRenderTargetMultiplier>1.250000</HMDRenderTargetMultiplier><TerrainCheckerboardRenderingEnabled>false</TerrainCheckerboardRenderingEnabled><NewField>preserve</NewField></Root>"),["GraphicsConfigurationOverride.xml"]=Encoding.UTF8.GetBytes("<GraphicsConfig><!-- keep --><GalaxyBackground><High><TextureSize>4096</TextureSize></High></GalaxyBackground><Planets><Ultra><TextureSize>4096</TextureSize></Ultra></Planets><GalaxyBackground><High><TextureSize>4096</TextureSize></High></GalaxyBackground><Envmap><High><TextureSize>1024</TextureSize><NumMips>10</NumMips></High></Envmap><GUIColour><Default><MatrixRed>0.4, 0.2, 1</MatrixRed></Default></GUIColour></GraphicsConfig>"),["StartPreset.start"]=Encoding.UTF8.GetBytes("High")};
void Assert(bool ok,string text="Assertion failed"){if(!ok)throw new Exception(text);}
void Throws(Action action){try{action();}catch(Exception){return;}throw new Exception("Expected failure, but action succeeded.");}
string NewFolder(){var p=Path.Combine(root,Guid.NewGuid().ToString("N"));Directory.CreateDirectory(p);return p;}
void Write(FileSet data,string folder){foreach(var(k,v)in data)File.WriteAllBytes(Path.Combine(folder,k),v);}
FileSet Enhanced(FileSet source){var data=source.Clone();GraphicsModel.SetTexture(data,definitions,"Planets",4096);GraphicsModel.SetTexture(data,definitions,"GalaxyBackground",4096);return data;}
var tests=new List<(string Name,Action Run)>();
void Test(string name,Action action)=>tests.Add((name,action));

Test("Medium selectors ignore dormant Ultra/High overrides",()=>{var b=Baseline();Assert(GraphicsModel.Texture(b,definitions,"Planets").Value=="1024");Assert(GraphicsModel.Texture(b,definitions,"GalaxyBackground").Value=="1024");});
Test("Combined hi-res changes only selected texture values",()=>{var b=Baseline();var e=Enhanced(b);Assert(GraphicsModel.Texture(e,definitions,"Planets").Value=="4096");Assert(GraphicsModel.Texture(e,definitions,"GalaxyBackground").Value=="4096");Assert(e.Where(x=>x.Key!="GraphicsConfigurationOverride.xml").All(x=>x.Value.SequenceEqual(b[x.Key])));var d=GraphicsModel.Diff(b,e);Assert(d.Count==2);Assert(d.All(x=>x.Path.Contains("Medium[1]/TextureSize[1]")));Assert(Encoding.UTF8.GetString(e["GraphicsConfigurationOverride.xml"]).Contains("<!-- keep -->"));});
Test("Unknown overrides, HUD and environment mapping survive",()=>{var e=Enhanced(Baseline());var doc=XmlIO.Read(e["GraphicsConfigurationOverride.xml"]);Assert(doc.Root!.Element("GUIColour")!.Element("Default")!.Element("MatrixRed")!.Value=="0.4, 0.2, 1");Assert(doc.Root.Elements("GalaxyBackground").Count()==2);Assert(doc.Root.Element("Envmap")!.Element("High")!.Element("NumMips")!.Value=="10");});
Test("Repeated sibling changes have distinct paths",()=>{var a=Baseline();var b=a.Clone();var doc=XmlIO.Read(b["GraphicsConfigurationOverride.xml"]);doc.Root!.Elements("GalaxyBackground").Last().Element("High")!.Element("TextureSize")!.Value="8192";b["GraphicsConfigurationOverride.xml"]=XmlIO.Write(doc);Assert(GraphicsModel.Diff(a,b).Single().Path.Contains("GalaxyBackground[2]"));});
Test("Conflicting active duplicate values are ambiguous",()=>{var a=Baseline();GraphicsModel.Set(a,GraphicsModel.ActiveFile(a),"EnvironmentQuality","3");var d=XmlIO.Read(a["GraphicsConfigurationOverride.xml"]);d.Root!.Elements("GalaxyBackground").Last().Element("High")!.Element("TextureSize")!.Value="2048";a["GraphicsConfigurationOverride.xml"]=XmlIO.Write(d);Assert(GraphicsModel.Texture(a,definitions,"GalaxyBackground").Value=="Ambiguous");});
Test("Quality .fxcfg changes appear in comparison",()=>{var a=Baseline();var b=a.Clone();GraphicsModel.Set(b,GraphicsModel.ActiveFile(b),"EnvironmentQuality","3");Assert(GraphicsModel.Diff(a,b).Single().File.EndsWith(".fxcfg"));});
Test("Versions sort numerically",()=>{var b=Baseline();b["Custom.4.10.fxcfg"]=Baseline("4.10")["Custom.4.10.fxcfg"];Assert(GraphicsModel.ActiveFile(b)=="Custom.4.10.fxcfg");});
Test("Schema mismatch rejected",()=>{var b=Baseline();b["Custom.4.5.fxcfg"]=b["Custom.4.4.fxcfg"];Throws(()=>GraphicsModel.ActiveFile(b));});
Test("Malformed XML and external entities rejected",()=>{var b=Baseline();b["Bad.xml"]=Encoding.UTF8.GetBytes("<bad>");Throws(b.Validate);b["Bad.xml"]=Encoding.UTF8.GetBytes("<!DOCTYPE x [<!ENTITY e SYSTEM 'file:///secret'>]><x>&e;</x>");Throws(b.Validate);});
Test("Unsafe paths and executable filenames rejected",()=>{foreach(var name in new[]{"../Settings.xml","C:\\Settings.xml","other/Settings.xml","run.bat","x:stream.xml"})Assert(!FileSet.Allowed(name));});
Test("Immutable revisions retain byte-exact original",()=>{var s=new ProfileStore(NewFolder());var b=Baseline();var p=s.Save("Baseline","VR",b,definitions,"build",protect:true);var e=Enhanced(b);var q=s.Save("Baseline","VR",e,definitions,"build",parentId:p.Id);Assert(p.Number==1&&q.Number==2);Assert(s.Files(p.Id).Fingerprint()==b.Fingerprint());Assert(s.Get(p.Id).Protected);Assert(q.ParentId==p.Id);});
Test("Revision tampering detected",()=>{var s=new ProfileStore(NewFolder());var p=s.Save("A","VR",Baseline(),definitions,"build");File.AppendAllText(Path.Combine(s.Profiles,p.Id,"Graphics","Settings.xml")," ");Throws(()=>s.Files(p.Id));});
Test("Definition tampering detected",()=>{var s=new ProfileStore(NewFolder());var p=s.Save("A","VR",Baseline(),definitions,"build");File.AppendAllText(Path.Combine(s.Profiles,p.Id,"Definitions.xml")," ");Throws(()=>s.Definitions(p.Id));});
Test("Apply and restore preserve unrelated files",()=>{var dir=NewFolder();var b=Baseline();Write(b,dir);File.WriteAllText(Path.Combine(dir,"unrelated.txt"),"untouched");var service=new ApplyService(NewFolder(),()=>false);var e=Enhanced(b);service.Apply(dir,e,b.Fingerprint(),definitions,definitions,"build","build");Assert(FileSet.Read(dir).Fingerprint()==e.Fingerprint());service.RestorePrevious(dir,e.Fingerprint());Assert(FileSet.Read(dir).Fingerprint()==b.Fingerprint());Assert(File.ReadAllText(Path.Combine(dir,"unrelated.txt"))=="untouched");});
Test("Game running blocks apply without writing",()=>{var dir=NewFolder();var b=Baseline();Write(b,dir);var s=new ApplyService(NewFolder(),()=>true);Throws(()=>s.Apply(dir,Enhanced(b),b.Fingerprint(),definitions,definitions,"b","b"));Assert(FileSet.Read(dir).Fingerprint()==b.Fingerprint());});
Test("Stale preview blocks overwriting external edits",()=>{var dir=NewFolder();var b=Baseline();Write(b,dir);File.AppendAllText(Path.Combine(dir,"Settings.xml")," ");var changed=FileSet.Read(dir).Fingerprint();var s=new ApplyService(NewFolder(),()=>false);Throws(()=>s.Apply(dir,Enhanced(b),b.Fingerprint(),definitions,definitions,"b","b"));Assert(FileSet.Read(dir).Fingerprint()==changed);});
Test("Old schema cannot remove new .fxcfg",()=>{var dir=NewFolder();var b=Baseline();Write(b,dir);var s=new ApplyService(NewFolder(),()=>false);Throws(()=>s.Apply(dir,Baseline("4.3"),b.Fingerprint(),definitions,definitions,"b","b"));Assert(File.Exists(Path.Combine(dir,"Custom.4.4.fxcfg")));});
Test("Changed game build/definitions block apply",()=>{var dir=NewFolder();var b=Baseline();Write(b,dir);var s=new ApplyService(NewFolder(),()=>false);Throws(()=>s.Apply(dir,Enhanced(b),b.Fingerprint(),definitions,definitions,"old","new"));Throws(()=>s.Apply(dir,Enhanced(b),b.Fingerprint(),definitions,[],"b","b"));});
Test("Partial write failure restores exact baseline",()=>{var dir=NewFolder();var b=Baseline();Write(b,dir);var s=new ApplyService(NewFolder(),()=>false);Throws(()=>s.Apply(dir,Enhanced(b),b.Fingerprint(),definitions,definitions,"b","b",n=>{if(n==2)throw new IOException("Simulated disk write failure");}));Assert(FileSet.Read(dir).Fingerprint()==b.Fingerprint());Assert(s.List().Single().State=="Restored");});
Test("Interrupted transaction recovers on next invocation",()=>{var dir=NewFolder();var b=Baseline();Write(b,dir);var history=NewFolder();bool running=false;var s=new ApplyService(history,()=>running);Throws(()=>s.Apply(dir,Enhanced(b),b.Fingerprint(),definitions,definitions,"b","b",n=>{if(n==3){running=true;throw new IOException("Simulated interruption");}}));Assert(s.List().Single().State=="Prepared");new ApplyService(history,()=>false).RecoverPending(dir);Assert(FileSet.Read(dir).Fingerprint()==b.Fingerprint());});
Test("Rollback protects external changes",()=>{var dir=NewFolder();var b=Baseline();Write(b,dir);var s=new ApplyService(NewFolder(),()=>false);s.Apply(dir,Enhanced(b),b.Fingerprint(),definitions,definitions,"b","b");File.AppendAllText(Path.Combine(dir,"Settings.xml")," ");var fingerprint=FileSet.Read(dir).Fingerprint();Throws(()=>s.RestorePrevious(dir,fingerprint));Assert(FileSet.Read(dir).Fingerprint()==fingerprint);});
Test("Rollback removes only files created by its transaction",()=>{var dir=NewFolder();var b=Baseline();b.Remove("GraphicsConfigurationOverride.xml");Write(b,dir);var e=Enhanced(b);var s=new ApplyService(NewFolder(),()=>false);s.Apply(dir,e,b.Fingerprint(),definitions,definitions,"b","b");s.RestorePrevious(dir,e.Fingerprint());Assert(!File.Exists(Path.Combine(dir,"GraphicsConfigurationOverride.xml")));Assert(FileSet.Read(dir).Fingerprint()==b.Fingerprint());});
Test("Migration preserves current-only fields",()=>{var old=Baseline("4.3");var doc=XmlIO.Read(old["Custom.4.3.fxcfg"]);doc.Root!.Element("NewField")!.Remove();doc.Root.Element("EnvironmentQuality")!.Value="3";old["Custom.4.3.fxcfg"]=XmlIO.Write(doc);var m=GraphicsModel.Migrate(old,Baseline());Assert(GraphicsModel.ActiveFile(m)=="Custom.4.4.fxcfg");Assert(GraphicsModel.Quality(m,"EnvironmentQuality")=="3");Assert(GraphicsModel.Quality(m,"NewField")=="preserve");});
Test("PresentMon import filters process and calculates percentiles",()=>{var file=Path.Combine(NewFolder(),"frames.csv");File.WriteAllText(file,"Application,SwapChainAddress,MsBetweenPresents\nOther.exe,0,999\nEliteDangerous64.exe,1,10\nEliteDangerous64.exe,1,20\nEliteDangerous64.exe,1,60\n");var summary=PresentMonImport.Read(file,"FLAT");Assert(summary.Count==3&&summary.P99Ms==60&&summary.HitchesOver50Ms==1);Assert(Math.Abs(summary.AverageFps-1000d/30)<.001);Throws(()=>PresentMonImport.Read(file,"VR"));});
Test("PresentMon multiple swapchains rejected",()=>{var file=Path.Combine(NewFolder(),"frames.csv");File.WriteAllText(file,"Application,SwapChainAddress,FrameTime\nEliteDangerous64.exe,1,10\nEliteDangerous64.exe,2,20\n");Throws(()=>PresentMonImport.Read(file,"FLAT"));});
Test("Missing GPU counters remain unavailable",()=>{Assert(GpuRecorder.Number("[N/A]")==null);Assert(GpuRecorder.Number("NaN")==null);Assert(GpuRecorder.Number("4096")==4096);});
Test("Apply blocks a mixed profile when an extra live graphics file exists",()=>{var dir=NewFolder();var b=Baseline();Write(b,dir);File.WriteAllText(Path.Combine(dir,"Extra.xml"),"<Extra>preserve</Extra>");var current=FileSet.Read(dir);var service=new ApplyService(NewFolder(),()=>false);Throws(()=>service.Apply(dir,Enhanced(b),current.Fingerprint(),definitions,definitions,"b","b"));Assert(FileSet.Read(dir).Fingerprint()==current.Fingerprint());Assert(service.List().Count==0);});
Test("Live benchmark CSV can be read while its writer remains open",()=>{var store=new BenchmarkStore(NewFolder());var run=new BenchmarkRun();store.Save(run);using var recorder=new GpuRecorder(store,run);Assert(store.Samples(run.Id).Count==0);var path=Path.Combine(store.Folder(run.Id),"other.csv");using var writer=new StreamWriter(path){AutoFlush=true};writer.WriteLine("seconds,memory,util,temp,clock,power");writer.WriteLine("1,1024,50,40,1000,100");var second=new BenchmarkRun();store.Save(second);var secondPath=Path.Combine(store.Folder(second.Id),"gpu.csv");using var stream=new FileStream(secondPath,FileMode.Create,FileAccess.Write,FileShare.Read);using var liveWriter=new StreamWriter(stream){AutoFlush=true};liveWriter.WriteLine("seconds,memory,util,temp,clock,power");liveWriter.WriteLine("1,1024,50,40,1000,100");Assert(store.Samples(second.Id).Single().MemoryMiB==1024);});

Test("Comparison detects differences unique to the third preset",()=>{var a=Baseline();var b=a.Clone();var c=Enhanced(a);var rows=PresetComparison.Build(new[]{new ComparisonSource("A",a,definitions),new ComparisonSource("B",b,definitions),new ComparisonSource("C",c,definitions)},false,true);Assert(rows.Count==2);Assert(rows.All(r=>!r.Cells[0].Different&&!r.Cells[1].Different&&r.Cells[2].Different));Assert(rows.All(r=>r.Cells[0].Value=="1024"&&r.Cells[2].Value=="4096"));});
Test("Raw comparison preserves duplicate paths and absent values",()=>{var a=Baseline();var b=a.Clone();var xml=XmlIO.Read(b["GraphicsConfigurationOverride.xml"]);xml.Root!.Elements("GalaxyBackground").Last().Element("High")!.Element("TextureSize")!.Value="2048";b["GraphicsConfigurationOverride.xml"]=XmlIO.Write(xml);b["Extra.xml"]=Encoding.UTF8.GetBytes("<Extra>new</Extra>");var rows=PresetComparison.Build(new[]{new ComparisonSource("A",a,definitions),new ComparisonSource("B",b,definitions)},true,true);Assert(rows.Any(r=>r.Setting.Contains("GalaxyBackground[2]")&&r.Cells[1].Value=="2048"));Assert(rows.Any(r=>r.Source=="Extra.xml"&&r.Cells[0].Value=="— absent"));});
Test("Resolved comparison aligns historical schemas and normalises numbers",()=>{var a=Baseline();var b=Baseline("4.3");GraphicsModel.Set(b,"Custom.4.3.fxcfg","HMDRenderTargetMultiplier","1.25");var sources=new[]{new ComparisonSource("A",a,definitions),new ComparisonSource("B",b,definitions)};Assert(PresetComparison.Build(sources,false,true).Count==0);Assert(PresetComparison.Build(sources,false,false).Count>0);Assert(PresetComparison.Build(sources,true,true).Count>0);});
Test("Comparison reports missing definitions and atmosphere ambiguity",()=>{var a=Baseline();var b=Enhanced(a);var xml=XmlIO.Read(b["GraphicsConfigurationOverride.xml"]);xml.Root!.Add(new System.Xml.Linq.XElement("Planets",new System.Xml.Linq.XElement("Medium",new System.Xml.Linq.XElement("AtmosphereSteps",5),new System.Xml.Linq.XElement("AtmosphereSteps",6))));b["GraphicsConfigurationOverride.xml"]=XmlIO.Write(xml);var rows=PresetComparison.Build(new[]{new ComparisonSource("A",a,Array.Empty<byte>()),new ComparisonSource("B",b,definitions)},false,true);Assert(rows.Single(r=>r.Setting=="Planet atmosphere steps").Cells[1].Value=="Ambiguous");Assert(rows.Single(r=>r.Setting=="Planet texture size").Cells[0].Value=="Unknown");Assert(PresetComparison.Build(new[]{new ComparisonSource("A",a,definitions)},false,true).Count==0);});
Test("Inventory includes unknown settings and conflicting sources without modifying files",()=>{var files=Baseline();var fingerprint=files.Fingerprint();var rows=SettingsInventory.Build(files,definitions,false,false);Assert(rows.Any(r=>r.Path.EndsWith("NewField[1]")&&r.Value=="preserve"));Assert(rows.Count(r=>r.Setting=="Terrain checkerboard rendering")==2);Assert(rows.Where(r=>r.Setting=="Terrain checkerboard rendering").All(r=>r.Note.Contains("unresolved")));Assert(rows.Any(r=>r.Path.Contains("GalaxyBackground[2]")));Assert(files.Fingerprint()==fingerprint);});
Test("Inventory separates historical schemas and optional shipped definitions",()=>{var files=Baseline();files["Custom.4.3.fxcfg"]=Baseline("4.3")["Custom.4.3.fxcfg"];var current=SettingsInventory.Build(files,definitions,false,false);Assert(!current.Any(r=>r.Source=="Custom.4.3.fxcfg"));var full=SettingsInventory.Build(files,definitions,true,true);Assert(full.Any(r=>r.Source=="Custom.4.3.fxcfg"&&r.Note.Contains("Older")));Assert(full.Any(r=>r.Source=="Installed defaults (snapshot).xml"&&r.Path.Contains("WorkPerFrame")));Assert(SettingsInventory.Build(files,[],false,true).Count==current.Count);});
Test("Inventory preserves unknown AA mode and display fields",()=>{var files=Baseline();GraphicsModel.Set(files,"Custom.4.4.fxcfg","AAMode","99");files["DisplaySettings.xml"]=Encoding.UTF8.GetBytes("<DisplayConfig><ScreenWidth>5120</ScreenWidth><FullScreen>2</FullScreen></DisplayConfig>");var rows=SettingsInventory.Build(files,definitions,false,false);Assert(rows.Single(r=>r.Setting=="Anti-aliasing").Value=="99");Assert(rows.Any(r=>r.Setting=="Display resolution width"&&r.Value=="5120"));Assert(rows.Any(r=>r.Setting=="Fullscreen / window mode"));});
Test("Readable settings retain raw values and units",()=>{var files=Baseline();GraphicsModel.Set(files,"Custom.4.4.fxcfg","AAMode","1");GraphicsModel.Set(files,"Custom.4.4.fxcfg","GpuSchedulerMultiplier","0.7");var rows=SettingsInventory.Build(files,definitions,false,false);Assert(rows.Single(r=>r.Setting=="Anti-aliasing").DisplayValue=="FXAA");Assert(rows.Single(r=>r.Setting=="HMD image quality").DisplayValue=="1.25×");Assert(rows.Single(r=>r.Setting=="Terrain work").DisplayValue=="70%");Assert(rows.Single(r=>r.Setting=="Terrain work").Value=="0.7");Assert(SettingsInventory.FormatValue("MaxFramesPerSecond","60")=="60 FPS");Assert(SettingsInventory.FormatValue("TextureSize","4096")=="4096 px");Assert(SettingsInventory.FormatValue("AAMode","99").Contains("Unverified"));});
Test("Readable qualities use saved definitions without decoding override internals",()=>{var defs=Encoding.UTF8.GetBytes("<GraphicsConfig><SurfaceMaterial><Low><LocalisationName>L</LocalisationName></Low><Medium><LocalisationName>M</LocalisationName></Medium><High><LocalisationName>H</LocalisationName></High></SurfaceMaterial></GraphicsConfig>");var rootXml=XmlIO.Read(defs).Root;Assert(SettingsInventory.FormatValue("SurfaceMaterialQuality","2",rootXml)=="High");Assert(SettingsInventory.FormatValue("SurfaceMaterialQuality","2",rootXml,false)=="2");Assert(SettingsInventory.FormatValue("BlurEnabled","false")=="Off");Assert(SettingsInventory.FormatValue("SurfaceSamplerQuality","2")=="High");});
Test("Update keeps identity and history; stale updates rejected",()=>{var s=new ProfileStore(NewFolder());var p=s.Fork("Pilot","VR",Baseline(),definitions,"build","");var q=s.Update(p.Id,"FLAT",Enhanced(Baseline()),definitions,"build","change");Assert(s.Identity(p)==s.Identity(q)&&q.Number==2);Assert(s.Heads().Single().Id==q.Id);Assert(s.History(q.Id).Count==2);Assert(s.Files(p.Id).Fingerprint()==Baseline().Fingerprint());Throws(()=>s.Update(p.Id,"VR",Baseline(),definitions,"build","stale"));});
Test("Same-name forks remain distinct; protected updates rejected",()=>{var s=new ProfileStore(NewFolder());var p=s.Save("Pilot","VR",Baseline(),definitions,"build",protect:true);Throws(()=>s.Update(p.Id,"VR",Enhanced(Baseline()),definitions,"build",""));var q=s.Fork("Pilot","VR",Baseline(),definitions,"build","",p.Id);Assert(s.Heads().Count==2&&q.Number==1&&s.Identity(p)!=s.Identity(q));});
Test("Default preset preserves HUD, stereo and unspecified fields without source changes",()=>{var b=Baseline();var before=b.Fingerprint();var result=PresetDefaults.Create(b,Encoding.UTF8.GetBytes("<RenderOptions><EnvironmentQuality>3</EnvironmentQuality><StereoscopicMode>0</StereoscopicMode></RenderOptions>"));Assert(GraphicsModel.Quality(result,"EnvironmentQuality")=="3");Assert(GraphicsModel.Quality(result,"NewField")=="preserve");Assert(GraphicsModel.General(result,"StereoscopicMode")=="3");var overrides=XmlIO.Read(result["GraphicsConfigurationOverride.xml"]);Assert(overrides.Root!.Elements().Single().Name=="GUIColour");Assert(b.Fingerprint()==before);Throws(()=>PresetDefaults.Create(b,Encoding.UTF8.GetBytes("<Invalid/>")));});
Test("Delete hides entire preset while preserving history and independent forks",()=>{var s=new ProfileStore(NewFolder());var p=s.Fork("A","VR",Baseline(),definitions,"build","");var q=s.Update(p.Id,"VR",Enhanced(Baseline()),definitions,"build","");var f=s.Fork("A","VR",Baseline(),definitions,"build","",q.Id);s.Delete(q.Id);Assert(s.List().Single().Id==f.Id);Assert(s.History(q.Id).Count==2&&s.Files(p.Id).Fingerprint()==Baseline().Fingerprint());s.RestoreDeleted(p.Id);Assert(s.Heads().Count==2);s.Delete(f.Id);s.Delete(q.Id);Assert(s.List().Count==0&&s.HasRevisions);});
Test("Inventory editor addresses exact duplicate leaf and keeps source immutable",()=>{var b=Baseline();var before=b.Fingerprint();var row=SettingsInventory.Build(b,definitions,false,false).Single(r=>r.Path.Contains("GalaxyBackground[2]")&&r.Path.EndsWith("TextureSize[1]"));var changed=SettingEditor.Change(b,row,"2048");Assert(GraphicsModel.Diff(b,changed).Single().Path.Contains("GalaxyBackground[2]"));Assert(b.Fingerprint()==before);Throws(()=>SettingEditor.Change(b,row,"NaN"));Throws(()=>SettingEditor.Change(b,row,"4.5"));});
Test("Inventory editor handles attributes and refuses definitions and schema version",()=>{var b=Baseline();GraphicsModel.Set(b,"Settings.xml","GammaOffset","0.5");var doc=XmlIO.Read(b["Settings.xml"]);doc.Root!.SetAttributeValue("Example","old");b["Settings.xml"]=XmlIO.Write(doc);var rows=SettingsInventory.Build(b,definitions,false,true);var attr=rows.Single(r=>r.Path.EndsWith("/@Example"));var changed=SettingEditor.Change(b,attr,"new");Assert(XmlIO.Read(changed["Settings.xml"]).Root!.Attribute("Example")!.Value=="new");Throws(()=>SettingEditor.Change(b,rows.First(r=>r.Source=="Installed defaults (snapshot).xml"),"1"));Throws(()=>SettingEditor.Change(b,rows.First(r=>r.Path.EndsWith("/@MajorVersion")),"9"));});
Test("Inline multiplier accepts decimals after integer serialization and enforces bounds",()=>{var files=Baseline();GraphicsModel.Set(files,GraphicsModel.ActiveFile(files),"HMDRenderTargetMultiplier","1");var row=SettingsInventory.Build(files,definitions,false,false).Single(r=>r.Setting=="HMD image quality");var changed=SettingEditor.Change(files,row,"1.1");Assert(GraphicsModel.Quality(changed,"HMDRenderTargetMultiplier")=="1.1");Assert(GraphicsModel.Quality(files,"HMDRenderTargetMultiplier")=="1");Throws(()=>SettingEditor.Change(files,row,"0.1"));Throws(()=>SettingEditor.Change(files,row,"3"));Throws(()=>SettingEditor.Change(files,row,"NaN"));});
Test("Inline percentage accepts fractions after whole serialization",()=>{var files=Baseline();GraphicsModel.Set(files,GraphicsModel.ActiveFile(files),"LODDistanceScale","1");var row=SettingsInventory.Build(files,definitions,false,false).Single(r=>r.Setting=="Model draw distance");Assert(GraphicsModel.Quality(SettingEditor.Change(files,row,"0.7"),"LODDistanceScale")=="0.7");Throws(()=>SettingEditor.Change(files,row,"70"));Throws(()=>SettingEditor.Change(files,row,"-0.1"));});
int failures=0;foreach(var (name,action) in tests){try{action();Console.WriteLine("PASS "+name);}catch(Exception e){failures++;Console.WriteLine("FAIL "+name+" — "+e.Message);}}
Console.WriteLine($"{tests.Count-failures}/{tests.Count} tests passed. Isolated fixtures: {root}");return failures==0?0:1;
